baseURL = "https://safar-india.org"
title = "SAFAR"
theme = "universal"
languageCode = "en-us"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Enable comments by entering your Disqus shortname
# disqusShortname = ""

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-170265980-1"

# Define the number of posts per page
paginate = 10

[markup.goldmark.renderer]
unsafe= true

[menu]
[[menu.main]]
    identifier = "home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier = "what-we-do"
    name = "What We Do"
    url  = "/what-we-do/"
    weight = 2

[[menu.main]]
    identifier = "accountability-and-digital-technology"
    parent = "what-we-do"
    name = "Accountability and Digital Technology"
    url  = "/what-we-do/accountability-and-digital-technology/"
    weight = 2

[[menu.main]]
    identifier = "Strengthening participatory democracy"
    parent = "what-we-do"
    name = "Strengthening Participatory Democracy"
    url  = "/what-we-do/strengthening-participatory-democracy/"
    weight = 3

[[menu.main]]
    identifier = "state-citizen-interfaces"
    parent = "what-we-do"
    name = "State-Citizen Interfaces"
    url  = "/what-we-do/state-citizen-interfaces/"
    weight = 4

[[menu.main]]
    identifier = "law-and-policy"
    parent = "what-we-do"
    name = "Law and Policy"
    url  = "/what-we-do/law-and-policy/"
    weight = 5

[[menu.main]]
    identifier = "practice-to-theory"
    parent = "what-we-do"
    name = "Practice to Theory, Theory to Practice"
    url  = "/what-we-do/practice-to-theory/"
    weight = 6

[[menu.main]]
    identifier = "collaboration-with-peoples-campaigns"
    parent = "what-we-do"
    name = "SAFAR’s collaboration with Peoples’ Campaigns"
    url  = "/what-we-do/collaboration-with-peoples-campaigns/"
    weight = 7

[[menu.main]]
    identifier = "publications"
    name = "Publications"
    url  = "publications/"
    weight = 3

[[menu.main]]
    identifier = "opinions"
    parent = "publications"
    name = "Opinions"
    url  = "/publications/opinions/"
    weight = 1

[[menu.main]]
    identifier = "papers-and-briefs"
    parent = "publications"
    name = "Working Papers and Reports"
    url  = "/publications/papers-and-briefs/"
    weight = 2

[[menu.main]]
    identifier = "book-chapters"
    parent = "publications"
    name = "Book Chapters"
    url  = "/publications/book-chapters/"
    weight = 3

[[menu.main]]
    identifier = "about"
    name = "About Us"
    url  = "/about-us/"
    weight = 4

[[menu.main]]
    identifier = "the-team"
    parent = "about"
    name = "The Team"
    url  = "/about-us/the-team/"
    weight = 1

[[menu.main]]
    identifier = "advisory"
    parent = "about"
    name = "Advisory Body"
    url  = "/about-us/advisory/"
    weight = 2

[[menu.main]]
    identifier = "our-collaborators"
    parent = "about"
    name = "Our Collaborators"
    url  = "/about-us/our-collaborators/"
    weight = 3

# [[menu.main]]
#    identifier = "work-with-us"
#    name = "Work with us"
#    url  = "/work-with-us/"
#    weight = 5

[[menu.main]]
    identifier = "our-finances"
    name = "Our Finances"
    url  = "/our-finances/"
    weight = 5

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 6

[params]
    # viewMorePostLink = "/blog/"
    author = "DipeshAggarwal"
    defaultKeywords = ["safar", "social", "india", "accountability", "research"]
    mainSections = ["blog"]
    defaultDescription = "SAFAR - Social Accountability Forum for Action and Research"

    # Social media
    # facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    # twitter_site = "" # the Twitter handle of your site (without the '@')
    # default_sharing_image = "img/sharing-default.png"

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "yellow"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    # email = ""
    # contact_form_ajax = false

    about_us = "<p>Social Accountability Forum for Action and Research (SAFAR) is a collective of activists, researchers and development practitioners. We work at the interface of activism, research and policy to deepen institutions and practices of social accountability and improve access to welfare rights.</p>"
    copyright = "Copyright (c)2022; All Rights Reserved."

    # Format dates with Go's time formatting
    date_format = "2 January, 2006"

    # logo = "img/logo.png"
    # logo_small = "img/logo-small.png"
    # address = """"""
    # latitude = "-12.043333"
    # longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
